apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "release.id" . }}-ingestion-configmap
  labels:
    {{- include "release.labels" . | indent 4 }}
    component: ingestion-configmap
data:
{{ (tpl (.Files.Glob "configmap/*").AsConfig .) | indent 2 }}
