apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "release.id" . }}-ingestion-create-folders
  labels:
    {{- include "release.labels" . | indent 4 }}
    component: ingestion-create-folders
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  parallelism: 1
  completions: 1
  template: 
    metadata:
      labels:
        {{- include "app.labels" . | indent 8 }}
        component: ingestion-create-folders
    spec:
      {{- include "security.context" . | indent 6 }}
      {{- if .Values.hooks.createFolders.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.hooks.createFolders.image.pullSecret.name }}
      {{- else if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret.name }}
      {{- end}}
      containers: 
      - name: create-folders
        image: "{{ .Values.hooks.createFolders.image.repository }}:{{ .Values.hooks.createFolders.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | default .Values.hooks.createFolders.image.pullPolicy }}
        env:
        {{- include "security.context.env" . | indent 8 }}
        {{- include "hadoop.env" . | indent 8 }}
        - name: "ADDITIONAL_HADOOP_CONF"
          value: "{{- range $name, $value := .Values.hadoop.configuration }}-D{{ $name }}={{ $value }} {{ end }}"
        args:
        - "bash"
        - "hdfs"
        - "dfs"
        - "-mkdir"
        - "-p"
        - "file:///data/{{ .Values.volumes.nfsMetocVolume.subPath }}/{{ .Values.volumes.nfsMetocVolume.subFolders.locks }}"
        - "file:///data/{{ .Values.volumes.nfsMetocVolume.subPath }}/{{ .Values.volumes.nfsMetocVolume.subFolders.ncInput }}"
        - "file:///data/{{ .Values.volumes.nfsMetocVolume.subPath }}/{{ $.Values.volumes.nfsMetocVolume.subFolders.ncInput }}/tests/dataset-alti8-nrt-global-msla-h"
        {{- range $name, $dataset := .Values.datasets }}
        - "file:///data/{{ $.Values.volumes.nfsMetocVolume.subPath }}/{{ $.Values.volumes.nfsMetocVolume.subFolders.ncInput }}/{{ $dataset.relativeFolder }}"
        - "{{ $.Values.datasetsFolder }}/{{ $dataset.relativeFolder }}/data"
        - "{{ $.Values.datasetsFolder }}/{{ $dataset.relativeFolder }}/index"
        {{- end }}
        volumeMounts:
        - mountPath: /data
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.nfsMetocVolume.name }}
      restartPolicy: Never
